//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certifications
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> dateAdd { get; set; }
        public Nullable<System.DateTime> datePrint { get; set; }
        public Nullable<System.DateTime> dateShip { get; set; }
        public Nullable<System.DateTime> dateGet { get; set; }
        public int Pos_ID { get; set; }
        public Nullable<int> CertType_ID { get; set; }
        public Nullable<int> Attachment_ID { get; set; }
        public string DocDescription { get; set; }
    
        public virtual Attachments Attachments { get; set; }
        public virtual CertTypes CertTypes { get; set; }
        public virtual Pos Pos { get; set; }
    }
}
