//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosRanks
    {
        public int ID { get; set; }
        public int Rank { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string Description { get; set; }
        public Nullable<int> Pos_ID { get; set; }
        public Nullable<bool> ActiveRank { get; set; }
    
        public virtual Pos Pos { get; set; }
    }
}
